language: bash

sudo: required

branches:
  only:
    - master

services:
  - docker

script:
 - docker build --tag orleika/web-static .
 - docker run -d -p 80:80 orleika/web-static
 - sleep 5
 - curl -sSf localhost
